DROP TABLE IF EXISTS bill;
DROP TABLE IF EXISTS bill_item;
DROP TABLE IF EXISTS appointment;
DROP TABLE IF EXISTS shift;
DROP TABLE IF EXISTS cookie;
DROP TABLE IF EXISTS _user;
DROP TABLE IF EXISTS specialty;
DROP TYPE IF EXISTS _user_type;
